name: openGauss gitee repos mirror periodic job

on:
  pull_request:
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
    paths:
    - '.github/workflows/**'
  schedule:
    # Runs every hour
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the gitee/opengauss org repos to github/opengauss-mirror.
      uses: Yikun/hub-mirror-action@v0.08
      with:
        src: gitee/opengauss
        dst: github/opengauss-mirror
        dst_key: ${{ secrets.SYNC_GAUSS_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_GAUSS_TOKEN }}
        account_type: org
